# Enable the database chart
enabled: true

image:
  repository: "ghcr.io/mairie360/database"
  tag: "latest"
  pullSecret: "ghcr-secret"

persistence:
  enabled: true
  size: 2Gi

resources:
  requests:
    memory: "128Mi" # Divisé par 2
    cpu: "100m"
  limits:
    memory: "512Mi"

# Hardcoded environment variables for local run
env:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "mysecretpassword"
  POSTGRES_DB: "mairie_db"

# Vault is disabled as requested
vault:
  enabled: false