{{- range $apiName, $apiConfig := .Values.instances }}
{{- if $apiConfig.enabled }}
{{- $ctx := dict "root" $ "name" $apiName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $apiName }}
  labels:
    {{- include "apis.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $apiName }}
    app: {{ $apiName }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ include "apis.servicePort" $ctx }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "apis.instanceSelectorLabels" $ctx | nindent 4 }}
{{- end }}
{{- end }}
