{{- range $frontName, $frontConfig := .Values.instances }}
{{- if $frontConfig.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $frontName | lower }}
  labels:
    {{- include "fronts.labels" $ | nindent 4 }}
    app: {{ $frontName | lower }}
spec:
  replicas: {{ $frontConfig.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "fronts.selectorLabels" $ | nindent 6 }}
      app: {{ $frontName | lower }}
  template:
    metadata:
      labels:
        {{- include "fronts.labels" $ | nindent 8 }}
        app: {{ $frontName | lower }}
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers: 
        - name: {{ $frontName | lower }}
          image: "{{ $frontConfig.image.repository }}:{{ $frontConfig.image.tag | default "latest" }}"
          ports:
            - containerPort: {{ $frontConfig.port }}
          env:
            {{- include "fronts.commonEnv" $ | nindent 12 }}
            # Écrase dynamiquement le PORT du Dockerfile
            - name: PORT
              value: {{ $frontConfig.port | quote }}
            {{- if $frontConfig.env }}
            {{- toYaml $frontConfig.env | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ $frontConfig.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ $frontConfig.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- if $frontConfig.resources }}
            {{- toYaml $frontConfig.resources | nindent 12 }}
            {{- else }}
            {{- toYaml $.Values.resources | nindent 12 }}
            {{- end }}
{{- end }}
{{- end }}