apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fronts.fullname" . }}-access
spec:
  podSelector:
    matchLabels:
      component: frontend
  policyTypes:
    - Ingress
  ingress:
    # Autorise le trafic venant de l'Ingress Controller (Nginx)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
    # Port standard HTTP
    - ports:
        - protocol: TCP
          port: 80