{{- range $frontName, $frontConfig := .Values.instances }}
{{- if $frontConfig.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Release.Name }}-{{ $frontName | lower }}-access
  labels:
    {{- include "fronts.labels" $ | nindent 4 }}
    app: {{ $frontName | lower }}
spec:
  podSelector:
    matchLabels:
      {{- include "fronts.selectorLabels" $ | nindent 6 }}
      app: {{ $frontName | lower }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ $frontConfig.port }}
{{- end }}
{{- end }}