image:
  repository: "ghcr.io/mairie360/database"
  tag: "main-18242192009"

persistence:
  enabled: true
  size: "1Gi"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"

# Valeurs pour le Secret (variables d'environnement)
env:
  POSTGRES_USER: "prod_user"
  POSTGRES_PASSWORD: "prod_pass"
  POSTGRES_DB: "core_prod"
