apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database-prod
  namespace: prod
spec:
  provider: vault
  secretObjects:
  - secretName: shared-db-coreAPI-prod
    type: Opaque
    data:
      - objectName: DB_HOST
        key: DB_HOST
      - objectName: DB_PORT
        key: DB_PORT
      - objectName: DB_USER
        key: DB_USER
      - objectName: DB_PASSWORD
        key: DB_PASSWORD
      - objectName: DB_NAME
        key: DB_NAME
  parameters:
    roleName: "database-prod"
    vaultAddress: "https://vault.example.com"
    objects: |
      - objectName: "DB_HOST"
        secretPath: "secret/mairie360/shared-db-coreAPI/prod"
        secretKey: "DB_HOST"
      - objectName: "DB_PORT"
        secretPath: "secret/mairie360/shared-db-coreAPI/prod"
        secretKey: "DB_PORT"
      - objectName: "DB_USER"
        secretPath: "secret/mairie360/shared-db-coreAPI/prod"
        secretKey: "DB_USER"
      - objectName: "DB_PASSWORD"
        secretPath: "secret/mairie360/shared-db-coreAPI/prod"
        secretKey: "DB_PASSWORD"
      - objectName: "DB_NAME"
        secretPath: "secret/mairie360/shared-db-coreAPI/prod"
        secretKey: "DB_NAME"
