apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database-dev
  namespace: dev
spec:
  provider: vault
  secretObjects:                        # Facultatif, pour créer un Secret Kubernetes
  - secretName: shared-db-coreAPI-dev   # Nom du Secret Kubernetes créé
    type: Opaque
    data:
      - objectName: DB_HOST
        key: DB_HOST
      - objectName: DB_PORT
        key: DB_PORT
      - objectName: DB_USER
        key: DB_USER
      - objectName: DB_PASSWORD
        key: DB_PASSWORD
      - objectName: DB_NAME
        key: DB_NAME
  parameters:
    roleName: "database-dev"           # Nom du rôle Vault correspondant
    vaultAddress: "https://vault.example.com"  # Adresse de ton Vault
    objects: |
      - objectName: "DB_HOST"
        secretPath: "secret/mairie360/shared-db-coreAPI/dev"
        secretKey: "DB_HOST"
      - objectName: "DB_PORT"
        secretPath: "secret/mairie360/shared-db-coreAPI/dev"
        secretKey: "DB_PORT"
      - objectName: "DB_USER"
        secretPath: "secret/mairie360/shared-db-coreAPI/dev"
        secretKey: "DB_USER"
      - objectName: "DB_PASSWORD"
        secretPath: "secret/mairie360/shared-db-coreAPI/dev"
        secretKey: "DB_PASSWORD"
      - objectName: "DB_NAME"
        secretPath: "secret/mairie360/shared-db-coreAPI/dev"
        secretKey: "DB_NAME"
