{{- range $bffName, $bffConfig := .Values.instances }}
{{- if $bffConfig.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $bffName }}
  labels:
    app: {{ $bffName }}
    component: bff
spec:
  replicas: {{ $bffConfig.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ $bffName }}
  template:
    metadata:
      labels:
        app: {{ $bffName }}
        component: bff
    spec:
      {{/* Init Container pour attendre l'API */}}
      initContainers:
        - name: wait-for-api
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv {{ $.Release.Name }}-core-api 80; do echo 'Waiting for Core API...'; sleep 2; done;"]
      containers:
        - name: {{ $bffName }}
          image: "{{ $bffConfig.image.repository }}:{{ $bffConfig.image.tag | default "latest" }}"
          ports:
            - containerPort: 4000
          env:
            {{- include "bffs.commonEnv" $ | nindent 12 }}
            {{- if $bffConfig.env }}
            {{- toYaml $bffConfig.env | nindent 12 }}
            {{- end }}
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
{{- end }}
{{- end }}