apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bff-security-policy
spec:
  podSelector:
    matchLabels:
      component: bff
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          component: front # Seuls les fronts peuvent appeler le BFF
    ports:
    - protocol: TCP
      port: 4000