apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bffs.fullname" . }}-access
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: bff
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              # On utilise le label exact constaté sur ton pod front
              app.kubernetes.io/component: frontend 
      ports:
        - protocol: TCP
          port: 4000