{{- if (($.Values.global).networkPolicy).enabled }}
# Les BFFs acceptent le trafic des fronts et des autres BFFs.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bffs.fullname" . }}-allow-from-fronts
  labels:
    {{- include "bffs.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: bff
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: bff
{{- end }}
