# Configuration globale pour le Hub ArgoCD de Mairie360
global:
  domain: "mairie360-eip.fr"

# Configuration de l'accès et des paramètres du serveur ArgoCD
server:
  insecure: true # Mis à true si tu gères la terminaison SSL directement au niveau de ton Ingress Nginx
  extraArgs:
    - --insecure

# Configuration de l'Ingress pour exposer ton ArgoCD Hub en HTTPS
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - argocd-hub.mairie360-eip.fr. # Ou ton sous-domaine de transition (ex: argocd-new.mairie360-eip.fr)
  tls:
    - secretName: argocd-hub-server-tls
      hosts:
        - argocd-hub.mairie360-eip.fr.
