mairie360-stack:
  # 1. Image
  image:
    pullSecretData: "eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJVWFZsYm5ScGJuUnVjbXc2WjJod1gwOUVjVUV5YzJ0dlIwY3diR001UjBSd1VHOUtUV1pGY1VWUVUwZ3pNak4zVHpkS1FnPT0ifX19"
    repository: ghcr.io/mairie360/core
    tag: "latest"

  # 2. Ingress
  ingress:
      enabled: true
      host: staging.mairie360-eip.fr

  # 3. Service (AJOUTE CE BLOC ICI)
  service:
    type: ClusterIP
    port: 80

  # 4. Database
  database:
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
    persistence:
      size: "2Gi"
      storageClass: "local-path"
    env:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "stagingpassword123"
      POSTGRES_DB: "mairie_db_staging"

  # 5. Liquibase
  # Note : Assure-toi que l'image.tag est bien défini ici si ton chart en a besoin
  liquibase:
    image:
      tag: "staging-latest"
    db:
      host: "local-staging-database"
      port: 5432
      name: "mairie_db_staging"
    secretName: "local-staging-database-secret"

  # 6. Redis
  redis:
    enabled: true