apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mairie360-db
  namespace: argocd
  annotations:
    # 1. Liste des images à surveiller
    argocd-image-updater.argoproj.io/image-list: db=ghcr.io/mairie360/database, migrations=ghcr.io/mairie360/liquibase-migrations

    # 2. Stratégies de mise à jour (latest pour ton dev, tu pourras mettre semver en prod)
    argocd-image-updater.argoproj.io/db.update-strategy: latest
    argocd-image-updater.argoproj.io/migrations.update-strategy: latest

    # 3. LE MAPPING : On lie l'image trouvée à la variable exacte dans tes values Helm
    argocd-image-updater.argoproj.io/db.helm.image-name: database.image
    argocd-image-updater.argoproj.io/migrations.helm.image-name: liquibase.image

    # 4. MODE DÉCENTRALISÉ : Argo écrit dans sa propre mémoire, pas de commit sur ton Git
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mairie360/infra.git'
    path: mairie360 # Vérifie que c'est bien le dossier de ton Chart
    targetRevision: HEAD
    helm:
      # Valeurs initiales (seront surchargées par l'Image Updater)
      values: |
        database:
          enabled: true
          image: ghcr.io/mairie360/database
          syncWave: 1
        liquibase:
          enabled: true
          image: ghcr.io/mairie360/liquibase-migrations
          syncWave: 2
        redis:
          enabled: false
        gateway:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true