apiVersion: v2
name: mairie360-stack
description: Umbrella chart pour Mairie360
type: application
version: 0.1.0

dependencies:
  - name: database
    version: "0.1.0"
  - name: redis
    version: "0.1.0"
  - name: liquibase
    version: "0.1.0"
  - name: APIs
    version: "0.1.0"
  - name: BFFs
    version: "0.1.0"
  - name: Fronts
    version: "0.1.0"