apiVersion: v2
name: mairie360-stack
description: Umbrella chart Mairie360 — Postgres, Redis, migrations, Keycloak, APIs, BFFs, Fronts
type: application
version: 0.6.0
appVersion: "0.6.0"

dependencies:
  - name: database
    version: "0.3.0"
  - name: redis
    version: "0.3.0"
  - name: liquibase
    version: "0.3.0"
  - name: backup
    version: "0.1.0"
  - name: keycloak
    version: "0.1.0"
  - name: APIs
    version: "0.4.0"
  - name: BFFs
    version: "0.3.0"
  - name: Fronts
    version: "0.3.0"
