apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-local
spec:
  acme:
    email: quentin.tennerel@epitech.eu
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-local-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx