image:
  pullSecretData: "eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJVWFZsYm5ScGJuUnVjbXc2WjJod1gwOUVjVUV5YzJ0dlIwY3diR001UjBSd1VHOUtUV1pGY1VWUVUwZ3pNak4zVHpkS1FnPT0ifX19"
  repository: ghcr.io/mairie360/core
  tag: "0.1.0"

# 2. Ingress
ingress:
  enabled: true
  className: "nginx"
  clusterIssuer: "letsencrypt-local"
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: prod.mairie360-eip.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: "local-prod-mairie360-stack-gateway"
          servicePort: 80
  tls:
    - secretName: prod-mairie360-tls
      hosts:
        - prod.mairie360-eip.fr

# 3. Service
service:
  type: ClusterIP
  port: 80

# 4. Database
database:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
  persistence:
    size: "10Gi"
    storageClass: "local-path"
  env:
    POSTGRES_USER: "postgres_admin"
    POSTGRES_PASSWORD: "prod_db_mdp"
    POSTGRES_DB: "mairie_db_prod"

# 5. Liquibase
liquibase:
  image:
    tag: "0.1.0"
  db:
    host: "local-prod-database"
    port: 5432
    name: "mairie_db_prod"
  secretName: "local-prod-database-secret"

# 6. Redis
redis:
  enabled: true
  
# 7. APIs
APIs:
  instances:
    core-api:
      enabled: true
      image:
        tag: "latest" # On utilise l'image stable
        repository: ghcr.io/mairie360/core-api

# 8. BFFs
BFFs:
  instances:
    bff-user:
      enabled: true
      image:
        tag: "latest" # On utilise l'image stable
        repository: ghcr.io/mairie360/bff-user
      env:
        - name: APP_NAME
          value: "BFF User Production"
          
# 9. Fronts
Fronts:
  instances:
    projects-front:
      enabled: true
      image:
        repository: ghcr.io/mairie360/projects-front
        tag: "latest"