image:
  pullSecretData: "eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJVWFZsYm5ScGJuUnVjbXc2WjJod1gwOUVjVUV5YzJ0dlIwY3diR001UjBSd1VHOUtUV1pGY1VWUVUwZ3pNak4zVHpkS1FnPT0ifX19"
  repository: ghcr.io/mairie360/core
  tag: "0.1.0"
  
# 2. Global
global:
  domain: "mairie360-eip.fr"

# 3. Ingress
ingress:
  enabled: true
  className: "nginx"
  clusterIssuer: "letsencrypt-local"
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: prod.mairie360-eip.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: "local-prod-fronts"
          servicePort: 80
  tls:
    - secretName: prod-mairie360-tls
      hosts:
        - prod.mairie360-eip.fr

# 4. Service
service:
  type: ClusterIP
  port: 80

# 5. Database
database:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
  persistence:
    size: "10Gi"
    storageClass: "local-path"
  env:
    POSTGRES_USER: "postgres_admin"
    POSTGRES_PASSWORD: "prod_db_mdp"
    POSTGRES_DB: "mairie_db_prod"

# 6. Liquibase
liquibase:
  image:
    tag: "0.1.0"
  db:
    host: "local-prod-database"
    port: 5432
    name: "mairie_db_prod"
  secretName: "local-prod-database-secret"

# 7. Redis
redis:
  enabled: true
  
# 8. APIs
APIs:
  instances:
    core-api:
      enabled: true
      image:
        tag: "latest" # On utilise l'image stable
        repository: ghcr.io/mairie360/core-api
        
    project-api:
        enabled: true
        image:
          tag: "latest"
          repository: ghcr.io/mairie360/project-api
        
    calendar-api:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/calendar-api
        
    message-api:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/message-api
        
    email-api:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/email-api
        
    files-api:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/files-api
        
    elearning-api:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/elearning-api

# 9. BFFs
BFFs:
  instances:
    user-bff:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/bff-user
        
    project-bff:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/bff-project
        
    calendar-bff:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/bff-calendar
        
    message-bff:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/bff-message
        
    email-bff:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/bff-email
        
    files-bff:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/bff-files
        
    elearning-bff:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/bff-elearning
          
# 10. Fronts
Fronts:
  instances:
    login-front:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/login-front
        
    project-front:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/projects-front
        
    calendar-front:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/calendar-front
        
    message-front:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/message-front
        
    email-front:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/email-front
        
    files-front:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/files-front
        
    elearning-front:
      enabled: true
      image:
        tag: "latest"
        repository: ghcr.io/mairie360/elearning-front