# -----------------------------
# Valeurs globales pour l'environnement dev
# -----------------------------
global:
  namespace: dev
  imagePullPolicy: IfNotPresent
  domain: "mairie360.dev"

service:
  type: ClusterIP

# -----------------------------
# Références d'accès pour les services Backend
# Ces valeurs seront injectées dans les variables d'env du Back
# -----------------------------
dataAccess:
  postgresql:
    host: mairie360-database
    port: 5432
    database: "core_dev"
  redis:
    host: mairie360-redis-master
    port: 6379

# -----------------------------
# Sous-charts activés et configurés pour dev
# -----------------------------

database:
  image:
    tag: "main-18242192009"
  env:
    POSTGRES_PASSWORD: "dev_pass"
    POSTGRES_DB: "core_dev"
  persistence:
    size: "1Gi"
    storageClass: "local-path" # comment for local run

redis:
  enabled: true
  replicaCount: 1
  image:
    tag: "7.2.0"
  redis:
    password: "devpassword"
  persistence:
    enabled: false
  config:
    maxmemory: "256mb"
    maxmemory-policy: "allkeys-lru"

liquibase:
  image:
    repository: ghcr.io/mairie360/liquibase-migrations
    tag: "dev-latest"
  db:
    # On réutilise les valeurs définies dans dataAccess pour rester cohérent
    host: mairie360-database
    port: 5432
    name: "core_dev"