# -----------------------------
# Valeurs globales pour l'environnement dev
# -----------------------------
global:
  namespace: dev
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"

# -----------------------------
# Sous-charts activés et configurés pour dev
# -----------------------------
database:
  image:
    tag: "main-18242192009"
  env:
    POSTGRES_PASSWORD: "dev_pass"
    POSTGRES_DB: "core_dev"
  persistence:
    size: "1Gi"

  redis:
    enabled: true
    replicaCount: 1
    image:
      tag: "7.2.0"          # tag que tu veux utiliser pour dev
    redis:
      password: "devpassword" # mot de passe Redis pour dev
    persistence:
      enabled: false
    config:
      maxmemory: "256mb"
      maxmemory-policy: "allkeys-lru"
