apiVersion: v1
kind: Secret
metadata:
  name: github-org-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/mairie360 # L'URL de ton organisation
  password: ghp_votre_token_ici    # GitHub Personal Access Token
  username: gitops-bot             # Nom d'utilisateur factice