apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    app: {{ include "database.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "database.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "database.name" . }}
    spec:
      containers:
        - name: database
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "database.fullname" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "database.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "database.fullname" . }}-secret
                  key: POSTGRES_DB
      imagePullSecrets:
        - name: ghcr-secret
