{{- if .Values.image.pullSecretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.pullSecretData }}
{{- end }}
