apiVersion: v1
kind: Service
metadata:
  name: {{ include "mairie360.fullname" . }}-gateway
spec:
  type: ClusterIP # Pas besoin de LoadBalancer si tu as un Ingress
  ports:
    - port: 80
      targetPort: 80 # Aligne-le sur le port de ton container front
      protocol: TCP
      name: http
  selector:
    # Doit matcher le label 'app' ou 'app.kubernetes.io/name' de ton pod front
    app.kubernetes.io/name: fronts