apiVersion: v1
kind: Service
metadata:
  name: {{ include "mairie360.fullname" . }}-gateway
  labels:
    app: {{ include "mairie360.fullname" . }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
    - port: 80
      targetPort: 8080 # Le port sur lequel ton application écoute
      protocol: TCP
      name: http
  selector:
    app: {{ include "mairie360.fullname" . }}-backend # Doit correspondre aux labels de ton Deployment