# Valeurs par défaut du sous-chart liquibase
image:
  repository: ghcr.io/mairie360/liquibase-migrations
  tag: latest

db:
  host: "database"
  port: 5432
  name: "core"

# Ces champs sont optionnels si ton Dockerfile gère déjà le reste
changelogFile: "changelog.xml"